/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellersIdRouteImport } from './routes/sellers.$id'
import { Route as ProductsIdRouteImport } from './routes/products.$id'

const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersIdRoute = SellersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SellersRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/meals': typeof MealsRoute
  '/moments': typeof MomentsRoute
  '/products': typeof ProductsRouteWithChildren
  '/sell': typeof SellRoute
  '/sellers': typeof SellersRouteWithChildren
  '/products/$id': typeof ProductsIdRoute
  '/sellers/$id': typeof SellersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/meals': typeof MealsRoute
  '/moments': typeof MomentsRoute
  '/products': typeof ProductsRouteWithChildren
  '/sell': typeof SellRoute
  '/sellers': typeof SellersRouteWithChildren
  '/products/$id': typeof ProductsIdRoute
  '/sellers/$id': typeof SellersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/meals': typeof MealsRoute
  '/moments': typeof MomentsRoute
  '/products': typeof ProductsRouteWithChildren
  '/sell': typeof SellRoute
  '/sellers': typeof SellersRouteWithChildren
  '/products/$id': typeof ProductsIdRoute
  '/sellers/$id': typeof SellersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/cart'
    | '/checkout'
    | '/meals'
    | '/moments'
    | '/products'
    | '/sell'
    | '/sellers'
    | '/products/$id'
    | '/sellers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/cart'
    | '/checkout'
    | '/meals'
    | '/moments'
    | '/products'
    | '/sell'
    | '/sellers'
    | '/products/$id'
    | '/sellers/$id'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/cart'
    | '/checkout'
    | '/meals'
    | '/moments'
    | '/products'
    | '/sell'
    | '/sellers'
    | '/products/$id'
    | '/sellers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  MealsRoute: typeof MealsRoute
  MomentsRoute: typeof MomentsRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  SellRoute: typeof SellRoute
  SellersRoute: typeof SellersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/$id': {
      id: '/sellers/$id'
      path: '/$id'
      fullPath: '/sellers/$id'
      preLoaderRoute: typeof SellersIdRouteImport
      parentRoute: typeof SellersRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface SellersRouteChildren {
  SellersIdRoute: typeof SellersIdRoute
}

const SellersRouteChildren: SellersRouteChildren = {
  SellersIdRoute: SellersIdRoute,
}

const SellersRouteWithChildren =
  SellersRoute._addFileChildren(SellersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  MealsRoute: MealsRoute,
  MomentsRoute: MomentsRoute,
  ProductsRoute: ProductsRouteWithChildren,
  SellRoute: SellRoute,
  SellersRoute: SellersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
